#!/bin/bash

# Installs YouCompleteMe if it's present
if [ -e "$HOME"/.vim/bundle/YouCompleteMe/install.py ]; then
  cd ~/.vim/bundle/YouCompleteMe && \
    ./install.py --clang-completer --tern-completer
fi
